name: Build

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches-ignore:
      - main
      - nightly
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Install Nix dependencies
        uses: diamondburned/cache-install@main
        with:
          shell-file: shell.nix

      - name: Build
        run: npm i && ./build.js

      - name: Upload dist artifact
        uses: actions/upload-artifact@main
        with:
          name: dist
          path: dist
